import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';

part 'app_database.g.dart';

// ---------------------------------------------------------------------------
// Catalogs. Ledger is authoritative for catalog data, so the remote ids are
// used as primary keys. No SQLite foreign keys are declared between catalogs
// and expenses: a catalog refresh must never be blocked (or cascade) because a
// pending local expense references a row that disappeared on the server; such
// rows are displayed as "Unknown" and rejected by the server on upload.
// ---------------------------------------------------------------------------

/// `currency` — conversion is the factor to the backend default currency
/// (the default currency is the one whose conversion is exactly 1).
@DataClassName('CurrencyRow')
class Currencies extends Table {
  IntColumn get id => integer()();
  TextColumn get name => text()();
  TextColumn get symbol => text()();
  RealColumn get conversion => real()();

  @override
  Set<Column> get primaryKey => {id};
}

/// `wallet_group` — the logical, possibly multi-currency, account.
@DataClassName('WalletGroupRow')
class WalletGroups extends Table {
  IntColumn get id => integer()();
  TextColumn get name => text()();
  BoolColumn get isActive => boolean().withDefault(const Constant(true))();

  @override
  Set<Column> get primaryKey => {id};
}

/// `wallet` — exactly one currency per wallet.
@DataClassName('WalletRow')
@TableIndex(name: 'idx_wallets_currency', columns: {#currencyId})
class Wallets extends Table {
  IntColumn get id => integer()();
  TextColumn get name => text()();
  IntColumn get currencyId => integer()();

  @override
  Set<Column> get primaryKey => {id};
}

/// `wallet_member` — links wallets to wallet groups.
@DataClassName('WalletMemberRow')
@TableIndex(name: 'idx_wallet_members_wallet', columns: {#walletId})
@TableIndex(name: 'idx_wallet_members_group', columns: {#walletGroupId})
class WalletMembers extends Table {
  IntColumn get id => integer()();
  IntColumn get walletId => integer()();
  IntColumn get walletGroupId => integer()();
  IntColumn get forwardWalletId => integer().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}

/// `cat_expense_type`.
@DataClassName('ExpenseTypeRow')
class ExpenseTypes extends Table {
  IntColumn get id => integer()();
  TextColumn get name => text()();
  TextColumn get icon => text().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}

/// `cat_vendor`.
@DataClassName('VendorRow')
class Vendors extends Table {
  IntColumn get id => integer()();
  TextColumn get name => text()();

  @override
  Set<Column> get primaryKey => {id};
}

/// `credit_card` (only what the app needs): used to hide wallet groups whose
/// credit card is not active.
@DataClassName('CreditCardRow')
@TableIndex(name: 'idx_credit_cards_group', columns: {#walletGroupId})
class CreditCards extends Table {
  IntColumn get id => integer()();
  IntColumn get walletGroupId => integer()();

  /// Ledger's `active` flag (1 = active).
  IntColumn get active => integer()();

  @override
  Set<Column> get primaryKey => {id};
}

// ---------------------------------------------------------------------------
// Expenses. The local primary key is independent from the Ledger id.
// ---------------------------------------------------------------------------

/// Local copy of `expense` plus synchronization bookkeeping.
@DataClassName('ExpenseRow')
@TableIndex(name: 'idx_expenses_remote_id', columns: {#remoteId}, unique: true)
@TableIndex(name: 'idx_expenses_sync_key', columns: {#syncKey}, unique: true)
@TableIndex(name: 'idx_expenses_buy_date', columns: {#buyDate})
@TableIndex(name: 'idx_expenses_wallet', columns: {#walletId, #buyDate})
@TableIndex(name: 'idx_expenses_expense_type', columns: {#expenseTypeId, #buyDate})
@TableIndex(name: 'idx_expenses_vendor', columns: {#vendorId, #buyDate})
@TableIndex(name: 'idx_expenses_sync_status', columns: {#syncStatus})
class Expenses extends Table {
  /// Local id, generated by SQLite.
  IntColumn get id => integer().autoIncrement()();

  /// Ledger id; null until the server acknowledged the expense.
  IntColumn get remoteId => integer().nullable()();

  /// Stable idempotency key (UUID v4) for expenses created on this device.
  /// Null for expenses downloaded from Ledger (they were never uploaded from here).
  TextColumn get syncKey => text().nullable()();

  IntColumn get walletId => integer()();
  IntColumn get expenseTypeId => integer()();
  IntColumn get vendorId => integer()();
  TextColumn get description => text().withLength(min: 1, max: 120)();
  RealColumn get total => real()();

  /// Optional expense-specific factor to the default currency.
  RealColumn get currencyFactor => real().nullable()();

  /// Date-only `YYYY-MM-DD`.
  TextColumn get buyDate => text().withLength(min: 10, max: 10)();
  IntColumn get sortId => integer().withDefault(const Constant(0))();

  /// `pending`, `failed` or `synced` (see `SyncStatus`).
  TextColumn get syncStatus => text()();
  TextColumn get syncError => text().nullable()();
  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get updatedAt => dateTime()();
}

/// Key/value store for synchronization metadata (last sync timestamps, etc.).
@DataClassName('SyncMetadataRow')
class SyncMetadata extends Table {
  TextColumn get key => text()();
  TextColumn get value => text()();

  @override
  Set<Column> get primaryKey => {key};
}

@DriftDatabase(tables: [
  Currencies,
  WalletGroups,
  Wallets,
  WalletMembers,
  ExpenseTypes,
  Vendors,
  CreditCards,
  Expenses,
  SyncMetadata,
])
class AppDatabase extends _$AppDatabase {
  AppDatabase(super.executor);

  /// Opens the on-device database file.
  factory AppDatabase.open() => AppDatabase(driftDatabase(name: 'ledger_mobile'));

  @override
  int get schemaVersion => 2;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) => m.createAll(),
        onUpgrade: (m, from, to) async {
          if (from < 2) {
            // v2: credit cards. Filled by the next full synchronization.
            await m.createTable(creditCards);
            await m.createIndex(idxCreditCardsGroup);
          }
        },
        beforeOpen: (details) async {
          await customStatement('PRAGMA foreign_keys = ON');
        },
      );
}
