-- Seed: cat_expense_type (85 filas)

INSERT INTO `cat_expense_type` (`id`, `description`, `icon`) VALUES
  (1, 'Restaurantes', 'entertainment/utensils'),
  (2, 'Cafeterías', 'coffee'),
  (3, 'Alimentos', 'set_meal'),
  (4, 'Transportes', 'train'),
  (5, 'Videojuegos', 'gamepad'),
  (6, 'Shopping', 'shopping_bag'),
  (7, 'Comics y Mangas', 'shopping/leanpub'),
  (8, 'Libros', 'menu_book'),
  (9, 'Tiendita o minisúper', 'shopping_basket'),
  (10, 'Regalos', 'card_giftcard'),
  (11, 'Entretenimiento', 'theater_comedy'),
  (12, 'Delivery', 'shopping/motorcycle'),
  (13, 'Saldo móvil', 'smartphone'),
  (14, 'In-App Purchasing', 'tablet-screen-button'),
  (15, 'Tiendas de bajo costo', 'store'),
  (16, 'Pastelerías y Repostería', 'cake'),
  (17, 'Compras en línea', 'shopping_bag'),
  (18, 'Arte y decoración', 'palette'),
  (19, 'Tecnología', 'microchip'),
  (20, 'Accesorios de cocina', 'kitchen-set'),
  (21, 'Manetenimiento del hogar', 'blender'),
  (22, 'Comida rápida', 'fastfood'),
  (23, 'Novela Ligera', 'menu_book'),
  (24, 'Supermercado', 'shopping_basket'),
  (25, 'Cines', 'confirmation_number'),
  (26, 'Farmacia', 'medication'),
  (27, 'Gasolina', 'local_gas_station'),
  (28, 'Educación', 'school'),
  (29, 'Mantenimiento de Vehiculos', 'directions_car'),
  (30, 'Viajes', 'flight'),
  (31, 'Gastos Médicos', 'medical_services'),
  (32, 'Seguros', 'health/assurance'),
  (33, 'Ropa y Moda', 'shopping/shirt'),
  (34, 'Donaciones', 'monetization_on'),
  (35, 'Servicios de Streaming', 'tv'),
  (36, 'Hoteles', 'hotel'),
  (37, 'Inversiones', 'trending_up'),
  (38, 'Apuestas', 'casino'),
  (39, 'Helados y Golosinas', 'icecream'),
  (40, 'Dentista', 'health/tooth'),
  (41, 'Bebidas y licores', 'sports_bar'),
  (42, 'Estetica y Barberia', 'content_cut'),
  (43, 'Herramientas', 'build'),
  (44, 'Mejoras del hogar', 'house-chimney-window'),
  (45, 'Prestamos', 'landmark'),
  (46, 'Casa y Hogar', 'house'),
  (47, 'Óptica-Optometría', 'visibility'),
  (48, 'Mensualidad', 'calendar_month'),
  (49, 'Pubs y Bares', 'sports_bar'),
  (50, 'Parking', 'local_parking'),
  (51, 'Lavandería y tintorería', 'dry_cleaning'),
  (52, 'Subscripción', 'local_activity'),
  (53, 'Carnicería', 'other/cow'),
  (54, 'Gastos fijos', 'landmark'),
  (55, 'Intereses', 'trending_down'),
  (56, 'Mantenimiento o Suministros', 'business'),
  (57, 'Impuestos', 'landmark'),
  (58, 'Transferencia', 'finance/money-transfer'),
  (59, 'PPR', 'savings'),
  (60, 'Disposición de efectivo', 'payments'),
  (61, 'Meses sin intereses', 'percent'),
  (62, 'Salud', 'favorite'),
  (63, 'Software o App', 'laptop-code'),
  (64, 'Anualidad', 'credit_card'),
  (65, 'Conciertos y eventos', 'local_activity'),
  (66, 'Adelantos', 'attach_money'),
  (67, 'Cashback', 'currency_exchange'),
  (68, 'Devolución', 'finance/coins'),
  (69, 'Anime figures', 'shopping_bag'),
  (70, 'Gaming PC', 'computer'),
  (71, 'Nutrición', 'health/nutrition'),
  (72, 'Cuidado personal', 'self_improvement'),
  (73, 'Productos para el cabello', 'shopping/pump-soap'),
  (74, 'Higiene Personal', 'shopping/clean-bottle'),
  (75, 'Bebidas Eventos', 'sports_bar'),
  (76, 'New TV', 'tv'),
  (77, 'Parking Eventos', 'local_parking'),
  (78, 'Comisión', 'receipt'),
  (79, 'Tramites', 'account_balance'),
  (80, 'Spa', 'entertainment/spa'),
  (81, 'Museos e Inst. de Arte', 'entertainment/art'),
  (82, 'Hiking', 'entertainment/person-hiking'),
  (83, 'Bebidas', 'shopping/bottle-water'),
  (84, 'Sport Events', 'entertainment/baseball'),
  (85, 'Dulces', 'shopping/candy-cane')
ON DUPLICATE KEY UPDATE `description` = VALUES(`description`), `icon` = VALUES(`icon`);
