-- Seed: cat_vendor (137 filas)

INSERT INTO `cat_vendor` (`id`, `description`) VALUES
  (1, 'Pizza Papa John\'s'),
  (2, 'Telcel'),
  (3, 'FFBE WOTV'),
  (4, 'Steam Games'),
  (5, 'Miniso'),
  (6, 'El Globo'),
  (7, 'Dominos'),
  (8, 'Amazon MX'),
  (9, 'Canvas Lab'),
  (10, 'Mercado Libre México'),
  (11, 'Copabanito'),
  (12, 'Subway'),
  (13, 'Sushi Roll'),
  (14, 'Maison Kayser'),
  (15, 'Aras Burger'),
  (16, 'Hooters'),
  (17, 'Taquearte'),
  (18, 'McDonald\'s'),
  (19, 'El Califa'),
  (20, 'El Tizoncito'),
  (21, 'Walmart Express'),
  (22, 'DDTECH'),
  (23, 'Google'),
  (24, 'Samsung'),
  (25, 'Cinemex'),
  (26, 'Cinépolis'),
  (27, 'Rappi'),
  (28, 'Temu'),
  (29, 'Fiesta Inn'),
  (30, 'Netflix'),
  (31, 'Izzi'),
  (32, 'GitHub'),
  (33, 'Spotify'),
  (34, 'NA'),
  (35, 'Xiaomi'),
  (36, 'Devlin'),
  (37, 'Twin Peaks'),
  (38, 'IHOP'),
  (39, 'Sanborns'),
  (40, 'Taberna Calacas'),
  (41, 'Shake Shack'),
  (42, 'American Eagle'),
  (43, 'Starbucks'),
  (44, 'Uber'),
  (45, 'Rappi Turbo'),
  (46, 'Taquería Copacabana'),
  (47, 'Wingstop'),
  (48, 'Tizoncito'),
  (49, 'La casa de Toño'),
  (50, 'Huequito'),
  (51, 'Sushi Izayaka'),
  (52, 'Costco'),
  (53, 'Mr. Blanco\'s'),
  (54, 'Tacos Xotepingo'),
  (55, 'Meta'),
  (56, 'Plaza Paseos Taxqueña'),
  (57, 'Oxxo'),
  (58, 'OpenAi'),
  (59, 'Crunchy Roll'),
  (60, 'Amazon Prime'),
  (61, 'G500'),
  (62, 'Shell'),
  (63, 'Pemex'),
  (64, 'Sacmex'),
  (65, 'Other'),
  (66, 'El Palacio de Hierro'),
  (67, 'Allianz México'),
  (68, 'Krox'),
  (69, 'Toyota Financial Services'),
  (70, 'Panini'),
  (71, 'Cheese Cake Factory'),
  (72, 'Liverpool'),
  (73, 'Porfirio\'s'),
  (74, 'Walmart'),
  (75, 'Soriana'),
  (76, 'Zapamundi'),
  (77, 'Ticketmaster'),
  (78, 'Boletia'),
  (79, 'Volaris'),
  (80, 'Justo'),
  (81, 'Microsoft'),
  (82, 'CyberPuerta'),
  (83, 'AXA México'),
  (84, 'Disney'),
  (85, 'Luuna'),
  (86, 'El fogoncito'),
  (87, 'Good smile Company'),
  (88, '7Eleven'),
  (89, 'Qobuz'),
  (90, 'Home Depot'),
  (91, 'Claude.AI'),
  (92, 'Cielito Lindo'),
  (93, 'Polymarket'),
  (94, 'Mitikah'),
  (95, 'Gyu Kaku'),
  (96, 'La Casa del Pastor'),
  (97, 'Oasis Coyoacan'),
  (98, 'Plaza Universidad'),
  (99, 'Santander'),
  (100, 'Gran Terraza Coapa'),
  (101, 'Centro Historico'),
  (102, 'Estadio GNP (Foro Sol)'),
  (103, 'Teatro Metropolitan'),
  (104, 'Farmacia Guadalajara'),
  (105, 'Dentista Carolina'),
  (106, 'Farmacia San Pablo'),
  (107, 'Vans'),
  (108, 'Airbnb'),
  (109, 'AICM'),
  (110, 'Denver Airport'),
  (111, '2nd & Charles'),
  (112, 'Coors Field'),
  (113, 'Meow Wolf'),
  (114, 'Ross'),
  (115, 'Target'),
  (116, 'Rocky Mountain National Park'),
  (117, 'Get your Guide'),
  (118, 'Bass Pro'),
  (119, 'Indian Hot Springs'),
  (120, 'Hayter\'s & Co'),
  (121, 'Casa Bonita'),
  (122, 'Market St CO'),
  (123, 'Lyons CO'),
  (124, 'South Park City'),
  (125, 'Estes Park CO'),
  (126, 'Aurora CO'),
  (127, 'Uptown Denver CO'),
  (128, 'JohnStown CO'),
  (129, 'Yard House'),
  (130, 'Red Rocks Amphitheatre'),
  (131, 'Five Below'),
  (132, 'Brown Dust 2'),
  (133, 'CFE'),
  (134, 'Stash X'),
  (135, 'Departamento 301'),
  (136, 'Farmacias del Ahorro'),
  (137, 'Masaryk')
ON DUPLICATE KEY UPDATE `description` = VALUES(`description`);
